[tool.poetry]
name = "peopleframe"
version = "0.1.0"
description = ""
authors = ["Peter Griess <pg@std.in>"]

[tool.poetry.dependencies]
osxphotos = "^0.46.1"
python = "^3.7"
pyxstar = "^0.1.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[tool.poetry.scripts]
peopleframe = "peopleframe.main:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
